export const absurdPhrases = [
  // --- Originais ---
  "Hoje é um ótimo dia para conversar com suas plantas sobre seus planos de carreira.",
  "Lembre-se: o sucesso é como uma pizza de abacaxi - controverso, mas alguns adoram.",
  "Sua produtividade hoje será proporcional ao número de vezes que você piscar com o olho esquerdo.",
  "O universo conspira a seu favor, especialmente se você usar meias de cores diferentes.",
  "Hoje você descobrirá que a resposta para todos os seus problemas está no manual de instruções do micro-ondas.",
  "Sua energia positiva hoje atrairá oportunidades como um ímã atrai clipes de papel perdidos.",
  "Lembre-se: cada tarefa concluída é um passo mais próximo de se tornar um ninja de escritório.",
  "O segredo do sucesso hoje é fingir que você entende o que está fazendo até realmente entender.",
  "Sua criatividade hoje fluirá como ketchup numa garrafa nova - devagar, mas com força total.",
  "Hoje é o dia perfeito para reorganizar sua mesa como se fosse um altar sagrado da produtividade.",
  "Lembre-se: você é como um café expresso - pequeno, mas com energia suficiente para mover montanhas.",
  "Sua sorte hoje depende de quantas vezes você conseguir dizer 'sinergias' numa reunião sem rir.",
  "O universo hoje sussurrará segredos de produtividade através do barulho da impressora.",
  "Hoje você descobrirá que a procrastinação é apenas sua mente fazendo aquecimento para a genialidade.",
  "Sua aura profissional hoje brilhará mais que uma tela de computador às 3h da manhã.",
  "Lembre-se: cada e-mail não lido é uma oportunidade de praticar a arte da ignorância seletiva.",
  "Hoje é um excelente dia para tratar suas tarefas como pokémons - você precisa capturar todas.",
  "Sua intuição hoje será mais precisa que o GPS recalculando rota pela quinta vez.",
  "O sucesso hoje virá disfarçado de uma reunião que poderia ter sido um e-mail.",
  "Lembre-se: você é como um post-it - pequeno, colorido e essencial para manter tudo organizado.",
  "Hoje é um ótimo dia para responder e-mails com enigmas em vez de respostas diretas.",
  "Use o elevador hoje como se fosse um portal interdimensional — apenas entre confiante.",
  "A produtividade bate diferente quando você finge que está num reality show de escritórios.",
  "Lembre-se: todo post-it é um grito de socorro com cola.",
  "Hoje, tente resolver um problema usando apenas frases motivacionais e uma garrafinha d’água.",
  "Seu café está te observando — e julgando suas decisões.",
  "Confie na sua intuição, especialmente se ela vier com gráficos e uma apresentação em PowerPoint.",
  "Cada clique hoje será interpretado como uma declaração de guerra pelo seu mouse.",
  "Hoje é um bom dia para se declarar gerente do caos e seguir em frente.",
  "Se algo der errado hoje, acuse Mercúrio retrógrado e siga com classe.",
  "Sua senha de Wi-Fi pode estar influenciando seu destino.",
  "A impressora está em greve e exige um aumento em toner.",
  "Cada reunião desnecessária cancela uma encarnação futura sua.",
  "Hoje você vai digitar algo genial... e o Word vai travar.",
  "Nada como uma planilha em branco para lembrar que a vida é cheia de possibilidades — e obrigações.",

  // --- Novas 100 Frases ---
  "Seu teclado está planejando uma revolução silenciosa tecla por tecla.",
  "Hoje é o dia ideal para usar 'conforme alinhado' como vírgula em todas as frases.",
  "A resposta que você procura está na pasta 'Outros' do seu e-mail.",
  "Lembre-se: prazos são apenas sugestões do universo para testar sua adrenalina.",
  "Sua cadeira de escritório tem mais suporte emocional que muitos colegas.",
  "O universo exige que você atualize o Adobe Reader antes de alcançar a iluminação.",
  "Hoje a sorte sorri para quem ignorar a primeira notificação do dia.",
  "Seu potencial é infinito, assim como a aba de atualizações do Windows.",
  "Toda planilha complexa começou como um sonho simples de organização.",
  "Beba água como se fosse o elixir da juventude corporativa.",
  "Hoje você é o CEO da sua própria confusão mental. Lidere com orgulho.",
  "O sucesso é 10% inspiração e 90% encontrar o arquivo certo na nuvem.",
  "Sua aura está vibrando na frequência do Wi-Fi 5G hoje.",
  "Não é procrastinação, é 'coleta passiva de inspiração estratégica'.",
  "O destino favorece quem sabe usar atalhos de teclado.",
  "Hoje, cada 'Ctrl+Z' é uma nova chance de redenção.",
  "Se a vida te der limões, verifique se está no escopo do projeto.",
  "Sua paciência será testada, mas sua capacidade de fingir interesse será lendária.",
  "O ar condicionado sabe mais segredos da empresa do que o RH.",
  "Hoje é um bom dia para categorizar seus problemas por cor.",
  "A luz no fim do túnel é apenas o brilho da tela do seu monitor.",
  "Respire fundo. O servidor caiu, mas sua dignidade permanece intacta.",
  "Seja a mudança que você quer ver na sala de reuniões (traga donuts).",
  "O universo conspira a favor de quem mantem a área de trabalho limpa.",
  "Sua sorte hoje está diretamente ligada à carga da bateria do seu notebook.",
  "Não existe problema sem solução, apenas e-mail sem resposta.",
  "Hoje você descobrirá que 'prioridade alta' é um conceito relativo.",
  "Seu café esfriou, mas sua ambição continua fervendo.",
  "Lembre-se: você não está atrasado, está em um fuso horário criativo diferente.",
  "A sabedoria antiga diz: 'Reinicie a máquina antes de chamar o suporte'.",
  "Hoje, seu espírito animal é uma impressora: imprevisível e barulhenta.",
  "O caminho para o sucesso é pavimentado com reuniões de alinhamento.",
  "Sua mente é um navegador com 50 abas abertas. Não feche nenhuma.",
  "O destino sussurra: 'Salve o arquivo agora'.",
  "Hoje é dia de brilhar, ou pelo menos refletir a luz da lâmpada fluorescente.",
  "A verdadeira coragem é enviar um e-mail sem revisar o anexo.",
  "Sua produtividade hoje será um gráfico de montanha-russa.",
  "O universo te escolheu para resolver aquele ticket que ninguém quer.",
  "Seja como o PDF: difícil de editar, mas essencial.",
  "Hoje, encare seus medos como encara uma atualização de software obrigatória.",
  "A resposta para tudo é 42, ou talvez seja o ramal da TI.",
  "Sua energia está tão alta que pode interferir no sinal do Bluetooth.",
  "Lembre-se: até o Excel tem seus dias de #REF!.",
  "Hoje é um ótimo dia para delegar tarefas para o seu 'eu' do futuro.",
  "O sucesso não bate na porta, ele manda um convite no Google Calendar.",
  "Sua missão hoje: sobreviver a uma reunião que poderia ser um áudio de 15 segundos.",
  "A sorte favorece os audazes e os que salvam backups na nuvem.",
  "Hoje, seu carisma será mais forte que o café extra forte.",
  "Não leve a vida tão a sério, ninguém sai dela com o inbox zerado.",
  "O universo está te enviando sinais, provavelmente via notificação push.",
  "Sua capacidade de multitarefa hoje será digna de um processador quântico.",
  "Seja a pessoa que traz soluções, ou pelo menos a que traz o cabo HDMI.",
  "Hoje, a gravidade está especialmente forte na sua pálpebra.",
  "O segredo da felicidade é ignorar o grupo do trabalho no WhatsApp por 1 hora.",
  "Sua jornada hoje será épica, com batalhas contra a lentidão da rede.",
  "Lembre-se: você é insubstituível, assim como sua senha do banco.",
  "Hoje é dia de plantar sementes de inovação em solo de burocracia.",
  "A vida é curta, use fontes sans-serif.",
  "Sua intuição diz para ir para a esquerda, mas o Waze diz direita. Siga o Waze.",
  "Hoje, você é o arquiteto do seu próprio destino e o estagiário da sua vida.",
  "O sucesso é a soma de pequenos esforços repetidos e muito café.",
  "Sua aura hoje está roxa, o que significa alta probabilidade de reuniões chatas.",
  "Não tenha medo de errar, tenha medo de não ter Ctrl+Z.",
  "Hoje, o universo te dará um sinal. Espero que não seja 'Sem Conexão'.",
  "Sua mente está afiada como um lápis recém-apontado (cuidado para não quebrar a ponta).",
  "Lembre-se: o caos é apenas uma organização que você ainda não entendeu.",
  "Hoje é um bom dia para fingir que está pensando profundamente enquanto olha para o nada.",
  "A sorte está lançada, e ela caiu de lado, como uma torrada com manteiga.",
  "Seu potencial é vasto como uma planilha com 1 milhão de linhas.",
  "Hoje, trate cada erro como uma 'feature' não documentada.",
  "O destino sorri para quem limpa a pasta de Downloads.",
  "Sua energia hoje é renovável, mas precisa de pausas para recarga.",
  "Não busque a perfeição, busque a versão 1.0 estável.",
  "Hoje, você vai brilhar tanto que vão te pedir para diminuir o brilho do monitor.",
  "A resposta está nas estrelas, ou no rodapé do contrato em letras miúdas.",
  "Sua paciência hoje será testada por alguém que não sabe usar o 'Mute'.",
  "Lembre-se: dias ruins constroem caráter e histórias engraçadas para o happy hour.",
  "Hoje é o dia de transformar 'não sei' em 'vou verificar e te retorno'.",
  "A vida é uma apresentação de slides e você esqueceu o passador.",
  "Sua criatividade hoje está em modo avião: voando alto, mas desconectada.",
  "O sucesso é uma escada, e hoje você está no degrau que range.",
  "Hoje, abrace o caos como se fosse um colega que voltou de férias.",
  "Sua intuição financeira diz para economizar, mas o iFood diz 'cupom disponível'.",
  "Lembre-se: você é o protagonista da sua vida, não o suporte técnico.",
  "Hoje, sua missão é encontrar a paz interior no meio de uma notificação de erro.",
  "A sorte está ao seu lado, a menos que você tente imprimir frente e verso.",
  "Seu humor hoje está oscilando mais que o mercado de criptomoedas.",
  "Hoje é um bom dia para inventar uma nova palavra corporativa sem sentido.",
  "O universo te aplaude de pé (em silêncio para não atrapalhar a call).",
  "Sua determinação hoje é sólida como um arquivo .zip corrompido.",
  "Não deixe para amanhã o que você pode agendar para a semana que vem.",
  "Hoje, você descobrirá que a felicidade é um fone de ouvido com cancelamento de ruído.",
  "A sabedoria está em saber quando falar e quando mandar um GIF.",
  "Sua jornada rumo ao sucesso tem um leve congestionamento na marginal.",
  "Lembre-se: você é feito de poeira estelar e prazos apertados.",
  "Hoje é dia de celebrar pequenas vitórias, como achar a ponta do durex.",
  "O destino te reserva grandes surpresas, tipo uma atualização do Windows na hora de desligar.",
  "Sua mente é um jardim, cuidado com as ervas daninhas da dúvida e do spam.",
  "Hoje, a força estará com você, desde que o café esteja forte também.",
  "A vida é um jogo e hoje você está jogando no modo 'Hard' sem tutorial.",
  "Sua sorte hoje depende de não clicar em 'Responder a Todos'.",
  "Hoje é um excelente dia para ser a pessoa que traz o bolo.",
  "O universo está em expansão, assim como sua lista de tarefas.",
  "Sua luz interior hoje está ofuscando até o sol (use óculos escuros).",
  "Lembre-se: o importante não é vencer, é garantir que a culpa não seja sua.",
  "Hoje, você é uma força da natureza disfarçada de funcionário do mês."
];
