export const absurdPhrases = [
  "Hoje é um ótimo dia para conversar com suas plantas sobre seus planos de carreira.",
  "Lembre-se: o sucesso é como uma pizza de abacaxi - controverso, mas alguns adoram.",
  "Sua produtividade hoje será proporcional ao número de vezes que você piscar com o olho esquerdo.",
  "O universo conspira a seu favor, especialmente se você usar meias de cores diferentes.",
  "Hoje você descobrirá que a resposta para todos os seus problemas está no manual de instruções do micro-ondas.",
  "Sua energia positiva hoje atrairá oportunidades como um ímã atrai clipes de papel perdidos.",
  "Lembre-se: cada tarefa concluída é um passo mais próximo de se tornar um ninja de escritório.",
  "O segredo do sucesso hoje é fingir que você entende o que está fazendo até realmente entender.",
  "Sua criatividade hoje fluirá como ketchup numa garrafa nova - devagar, mas com força total.",
  "Hoje é o dia perfeito para reorganizar sua mesa como se fosse um altar sagrado da produtividade.",
  "Lembre-se: você é como um café expresso - pequeno, mas com energia suficiente para mover montanhas.",
  "Sua sorte hoje depende de quantas vezes você conseguir dizer 'sinergias' numa reunião sem rir.",
  "O universo hoje sussurrará segredos de produtividade através do barulho da impressora.",
  "Hoje você descobrirá que a procrastinação é apenas sua mente fazendo aquecimento para a genialidade.",
  "Sua aura profissional hoje brilhará mais que uma tela de computador às 3h da manhã.",
  "Lembre-se: cada e-mail não lido é uma oportunidade de praticar a arte da ignorância seletiva.",
  "Hoje é um excelente dia para tratar suas tarefas como pokémons - você precisa capturar todas.",
  "Sua intuição hoje será mais precisa que o GPS recalculando rota pela quinta vez.",
  "O sucesso hoje virá disfarçado de uma reunião que poderia ter sido um e-mail.",
  "Lembre-se: você é como um post-it - pequeno, colorido e essencial para manter tudo organizado.",
  "Hoje é um ótimo dia para responder e-mails com enigmas em vez de respostas diretas.",
  "Use o elevador hoje como se fosse um portal interdimensional — apenas entre confiante.",
  "A produtividade bate diferente quando você finge que está num reality show de escritórios.",
  "Lembre-se: todo post-it é um grito de socorro com cola.",
  "Hoje, tente resolver um problema usando apenas frases motivacionais e uma garrafinha d’água.",
  "Seu café está te observando — e julgando suas decisões.",
  "Confie na sua intuição, especialmente se ela vier com gráficos e uma apresentação em PowerPoint.",
  "Cada clique hoje será interpretado como uma declaração de guerra pelo seu mouse.",
  "Hoje é um bom dia para se declarar gerente do caos e seguir em frente.",
  "Se algo der errado hoje, acuse Mercúrio retrógrado e siga com classe.",
  "Sua senha de Wi-Fi pode estar influenciando seu destino.",
  "A impressora está em greve e exige um aumento em toner.",
  "Cada reunião desnecessária cancela uma encarnação futura sua.",
  "Hoje você vai digitar algo genial... e o Word vai travar.",
  "Nada como uma planilha em branco para lembrar que a vida é cheia de possibilidades — e obrigações."
];
